name: dotnet package

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet-version: ['8.0.x']
        
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotent &{{ matrix.dotnet-version }}
              uses: actions/setup-dotent@v3
              with:
                dotnet-version: ${{matrix.dotnet-version}}
            - name: Display dotnet version
              run: dotnet --version
              
